version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
      - UMASK_SET=003
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
#      - NVIDIA_DRIVER_CAPABILITIES=all
#      - NVIDIA_VISIBLE_DEVICES=all
    group_add:
      - "989"
    volumes:
      - /mnt/1tb-hdd/server:/1tb-hdd
#      - /mnt/wd-black/server/:/wdBlack
      - /mnt/18tb-exo/:/18tb-exos
      - ./config/tdarr/server:/app/server
      - ./config/tdarr/config:/app/configs
      - ./transcode_cache:/temp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tdarr.rule=Host(`beautaapken.duckdns.org`) && PathPrefix(`/tdarr`)"
      - "traefik.http.routers.tdarr.service=tdarr"
      - "traefik.http.routers.tdarr.middlewares=tdarr-strip,tdarr-pathregex"
      - "traefik.http.middlewares.tdarr-strip.stripprefix.prefixes=/tdarr"
      - "traefik.http.routers.tdarr.entrypoints=https"
      - "traefik.http.routers.tdarr.tls=true"
      - "traefik.http.services.tdarr.loadbalancer.server.port=8265"
      - "traefik.http.middlewares.tdarr-pathregex.replacepathregex.regex=^/tdarr(.*)"
      - "traefik.http.middlewares.tdarr-pathregex.replacepathregex.replacement=$$1"
    devices:
      - /dev/dri:/dev/dri
#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            count: all
#            capabilities: [gpu]
