services:
# Download stuff
  qbit:
    image: linuxserver/qbittorrent
    container_name: qbit
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/18tb-exo/download:/downloads
    network_mode: service:vpn
    restart: always
    labels:
      - "traefik.enable=true"
      # adding a slash to the end
      - "traefik.http.routers.qbit.entrypoints=web"
      - "traefik.http.routers.qbit.rule=Host(`beautaapken.duckdns.org`) && PathPrefix(`/qbit`)"
      - "traefik.http.middlewares.qbit-redirect.redirectregex.regex=^(.*)/qbit$$"
      - "traefik.http.middlewares.qbit-redirect.redirectregex.replacement=$$1/qbit/"
      - "traefik.http.middlewares.qbit-strip.stripprefix.prefixes=/qbit/"
      # appropriate header change
      #      - "traefik.http.middlewares.qbit-headers.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
      #- "traefik.http.middlewares.qbit-headers.headers.customrequestheaders.Referer="
      #- "traefik.http.middlewares.qbit-headers.headers.customrequestheaders.Origin="
      - "traefik.http.routers.qbit.middlewares=qbit-strip,qbit-redirect"
      - "traefik.http.routers.qbit.entrypoints=https"
      - "traefik.http.routers.qbit.tls=true"
      - "traefik.http.routers.qbit.service=qbit"
      - "traefik.http.services.qbit.loadbalancer.server.port=8080"
    depends_on:
      - vpn

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/sonarr:/config
      - /mnt/1tb-hdd/server/:/1tb-hdd
      - /mnt/wd-black/server/:/wdBlack
      - /mnt/18tb-exo/:/18tb-exos
      - /mnt/18tb-exo/download:/downloads
    links:
      - vpn:qbittorrent
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`beautaapken.duckdns.org`) && PathPrefix(`/sonarr`)"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    depends_on:
      - qbit

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/radarr:/config
      - /mnt/1tb-hdd/server/:/1tb-hdd
      - /mnt/wd-black/:/wd-black
      - /mnt/18tb-exo/:/18tb-exos
      - /mnt/18tb-exo/download:/downloads
    links:
      - vpn:qbittorrent
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`beautaapken.duckdns.org`) && PathPrefix(`/radarr`)"
      - "traefik.http.routers.radarr.service=radarr"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    depends_on:
      - qbit

  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    restart: always
    volumes:
      - ./config/vpn:/vpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    security_opt:
      - label:disable
    labels:
      - "traefik.enable=false"

